name: pwsh-script

on:
  schedule:
    - cron: "0 16 * * *"
    - cron: "0 4 * * *"
    - cron: "0 10 * * *"

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Daily report.
        if: github.event.schedule == '0 16 * * *'
        continue-on-error: true
        env:
          BUPT_USERNAME: ${{ secrets.BUPT_USERNAME }}
          BUPT_PASSWORD: ${{ secrets.BUPT_PASSWORD }}
          DAILY_REPORT_FORM: ${{ secrets.DAILY_REPORT_FORM }}
        run: |
          ./daily_report.ps1
      - name: Regular check report.
        env:
          IS_AT_SCHOOL: ${{ secrets.IS_AT_SCHOOL }}
          BUPT_USERNAME: ${{ secrets.BUPT_USERNAME }}
          BUPT_PASSWORD: ${{ secrets.BUPT_PASSWORD }}
        run: |
          ./regular_report.ps1
